name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_chat_kits:
    path: ../

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # Media Packages (MANDATORY)
  record: ^6.1.2
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  audioplayers: ^6.5.1

  # Video Player
  video_player: ^2.9.2

  # Image/Video Saving
  #  image_gallery_saver: ^2.0.3
  permission_handler: ^12.0.1
  dio: ^5.7.0

  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.5
  video_compress: ^3.1.4
  visibility_detector: ^0.4.0+2
  share_plus: ^12.0.1
  firebase_database: ^12.1.2
  flutter_slidable: ^4.0.3
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  googleapis_auth: ^2.0.0
  http: ^1.6.0
  awesome_notifications: ^0.10.1
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/secrets/
